### PR TITLE
7 add feature to parse and ingest title-II data

### PR DESCRIPTION
**Pull request by sandeep-ps**
This PR is ready for review. It ingests EQIP and CSP data into the payments table and links the practice codes and practice categories. To test this PR, you can run the following example command:
```
cd src
python main.py -d <database_name> -u <username> -I -i -C -S -c
```
You need an entry for the \<database_name\> and \<username\> running in localhost in your local .pgpass file. Since we don't have an update feature on this CLI yet, starting with a fresh new database will be good and needed. Thanks

I have verified that the practice codes used in CSP and EQIP data are in the merged_practice_standards.csv.  Please let me know if you have any questions.

### CODE REVIEW

**Comment by sandeep-ps** [comment]
I have updated the reviewers' list. Previously, since this was a private repo, only one reviewer could be added. Please review this PR when you get a chance and share your feedback. Thanks.

**Comment by sandeep-ps** [comment]
Feedback from today's meeting: Create a top-level category called Miscellaneous and map all payment rows that do not fall in the current practice categories used in the front end.

**Comment by ywkim312** [comment]
I've got this error when I tried the command describe above. I am using python 3.10. I created fresh virtual environment and installed requirements using requirements.txt

```
Traceback (most recent call last):
  File "C:\Workspace-pdl\data-ingestion\src\main.py", line 2, in <module>
    from data_parser import DataParser
  File "C:\Workspace-pdl\data-ingestion\src\data_parser.py", line 2, in <module>
    import pandas as pd
  File "C:\venv\data-ingestion\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "C:\venv\data-ingestion\lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "C:\venv\data-ingestion\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\venv\data-ingestion\lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\venv\data-ingestion\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\venv\data-ingestion\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by navarroc** [comment]
> I've got this error when I tried the command describe above. I am using python 3.10. I created fresh virtual environment and installed requirements using requirements.txt
> 
> ```
> Traceback (most recent call last):
>   File "C:\Workspace-pdl\data-ingestion\src\main.py", line 2, in <module>
>     from data_parser import DataParser
>   File "C:\Workspace-pdl\data-ingestion\src\data_parser.py", line 2, in <module>
>     import pandas as pd
>   File "C:\venv\data-ingestion\lib\site-packages\pandas\__init__.py", line 22, in <module>
>     from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
>   File "C:\venv\data-ingestion\lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
>     from pandas.compat.numpy import (
>   File "C:\venv\data-ingestion\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
>     from pandas.util.version import Version
>   File "C:\venv\data-ingestion\lib\site-packages\pandas\util\__init__.py", line 2, in <module>
>     from pandas.util._decorators import (  # noqa:F401
>   File "C:\venv\data-ingestion\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
>     from pandas._libs.properties import cache_readonly
>   File "C:\venv\data-ingestion\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
>     from pandas._libs.interval import Interval
>   File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
> ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
> ```

What version of numpy are you using? My suspicion is we might need to pin numpy to a lower version. It would be good for you to compare with Sandeep to see if we either need to pin the version or fix the issue with using the latest numpy.

**Comment by navarroc** [comment]
Looks like numpy just jumped major versions to 2.0.0 from 1.26.4.

**Comment by ywkim312** [comment]
> Looks like numpy just jumped major versions to 2.0.0 from 1.26.4.

maybe we should set numpy to 1.26.4 or lower in requirements then?

**Comment by ywkim312** [comment]
> > I've got this error when I tried the command describe above. I am using python 3.10. I created fresh virtual environment and installed requirements using requirements.txt
> > ```
> > Traceback (most recent call last):
> >   File "C:\Workspace-pdl\data-ingestion\src\main.py", line 2, in <module>
> >     from data_parser import DataParser
> >   File "C:\Workspace-pdl\data-ingestion\src\data_parser.py", line 2, in <module>
> >     import pandas as pd
> >   File "C:\venv\data-ingestion\lib\site-packages\pandas\__init__.py", line 22, in <module>
> >     from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
> >   File "C:\venv\data-ingestion\lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
> >     from pandas.compat.numpy import (
> >   File "C:\venv\data-ingestion\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
> >     from pandas.util.version import Version
> >   File "C:\venv\data-ingestion\lib\site-packages\pandas\util\__init__.py", line 2, in <module>
> >     from pandas.util._decorators import (  # noqa:F401
> >   File "C:\venv\data-ingestion\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
> >     from pandas._libs.properties import cache_readonly
> >   File "C:\venv\data-ingestion\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
> >     from pandas._libs.interval import Interval
> >   File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
> > ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
> > ```
> 
> What version of numpy are you using? My suspicion is we might need to pin numpy to a lower version. It would be good for you to compare with Sandeep to see if we either need to pin the version or fix the issue with using the latest numpy.

I tried with numpy 1.26.4
This is my pip freeze
```

**Comment by navarroc** [comment]
> > Looks like numpy just jumped major versions to 2.0.0 from 1.26.4.
> 
> maybe we should set numpy to 1.26.4 or lower in requirements then?

Yes, we can probably just say numpy<2.0 so if the 1.* gets any fixes we pick them up. Unless we need anything from 2.0, that would be my suggestion. I tested this PR with 1.26.4 and it worked without issue. Note - I didn't check the data, I just verified it ran without issue.

**Comment by ywkim312** [comment]
> > > Looks like numpy just jumped major versions to 2.0.0 from 1.26.4.
> > 
> > 
> > maybe we should set numpy to 1.26.4 or lower in requirements then?
> 
> Yes, we can probably just say numpy<2.0 so if the 1.* gets any fixes we pick them up. Unless we need anything from 2.0, that would be my suggestion. I tested this PR with 1.26.4 and it worked without issue. Note - I didn't check the data, I just verified it ran without issue.

numpy < 2 looks to work but got another problem in database login... I will post it in another comment

**Comment by sandeep-ps** [comment]
Thanks for starting the review on this PR. I will go through these comments and respond today.

**Comment by sandeep-ps** [comment]
Hi, @ywkim312. It's better to use the .pgpass file to send the password. I had planned to phase that out (hence, the password provided through the command-line argument is not being used). I will restore it, but it's better to use the .pgpass file if possible. Please see the README and the text from the PR description:

>You need an entry for the <database_name> and <username> running in localhost in your local .pgpass file. Since we don't have an update feature on this CLI yet, starting with a fresh new database will be good and needed. Thanks

**Comment by ywkim312** [comment]
> Hi, @ywkim312. It's better to use the .pgpass file to send the password. I had planned to phase that out (hence, the password provided through the command-line argument is not being used). I will restore it, but it's better to use the .pgpass file if possible. Please see the README and the text from the PR description:
> 
> > You need an entry for the <database_name> and  running in localhost in your local .pgpass file. Since we don't have an update feature on this CLI yet, starting with a fresh new database will be good and needed. Thanks

Yes, I am using it but didn't work so I used the command.... I think that I need your help again. Sorry about that

**Comment by sandeep-ps** [comment]
Oh! Okay. Let me add the restore the db_password option.

**Comment by sandeep-ps** [comment]
Now, the CLI should also work with the password provided as an argument. Please check when you can and let me know if you see any issues. Thanks.

**Comment by ywkim312** [comment]
It started working. However, during the middle of the process, I got the following error (used the existing test table)

```
Traceback (most recent call last):
  File "C:\Workspace-pdl\data-ingestion\src\main.py", line 68, in <module>
    database.insert_data(title_i_data_parser.program_data)
  File "C:\Workspace-pdl\data-ingestion\src\pdl_database.py", line 176, in insert_data
    self.cursor.execute(sql_insert_query,
psycopg2.errors.UndefinedColumn: column "practice_category_id" of relation "payments" does not exist
LINE 1: ...itle_id, subtitle_id, program_id, sub_program_id, practice_c...
```

then I have created a new empty database and did command

python main.py --db_host fd-postgres-dev.ncsa.illinois.edu -d pdl-ywkim-test2 -u ccadmin -p <<password>> -I -i -C -c

```
Traceback (most recent call last):
  File "C:\Workspace-pdl\data-ingestion\src\main.py", line 32, in <module>
    database.initialize_tables()
  File "C:\Workspace-pdl\data-ingestion\src\pdl_database.py", line 116, in initialize_tables
    self.cursor.execute(sql_insert_query,
psycopg2.errors.UndefinedTable: relation "pdl.practices" does not exist
LINE 1: INSERT INTO pdl.practices (code, name, display_name, source)...
```

**Comment by sandeep-ps** [comment]
Hi, Yongwook; with this PR, the options have slightly changed. I had added an option to create schema (separate from creating the database) and updated the README earlier. Now, if you are starting with an empty database, you need to use the below options:
```-C -S -c -i -I```

Copying from README for reference:

```
usage: main.py [-h] --db_name DB_NAME [--db_user DB_USER] [--db_password DB_PASSWORD] [--db_host DB_HOST] [--db_port DB_PORT] [--drop_existing] [--log_level LOG_LEVEL] [--create-tables] [--create-database] [--create-schema]
               [--init-tables] [--insert-data]

Create a PostgreSQL database and tables, and insert/update data into the tables.

options:
  -h, --help            show this help message and exit
  --db_name DB_NAME, -d DB_NAME
                        Name of the database to create
  --db_user DB_USER, -u DB_USER
                        Username to connect to the database
  --db_password DB_PASSWORD, -p DB_PASSWORD
                        Password to connect to the database. We STRONGLY RECOMMEND using .pgpass file. If you use .pgpass file, this command-line argument can be ignored.
  --db_host DB_HOST     Host of the database
  --db_port DB_PORT     Port of the database
  --drop_existing, -x   Drop existing database if exists
  --log_level LOG_LEVEL, -l LOG_LEVEL
                        Log level
  --create-tables, -c   Create tables
  --create-database, -C
                        Construct database if it does not exist.
  --create-schema, -S   Create schema if it does not exist.
  --init-tables, -i     Initialize tables
  --insert-data, -I     Insert data
```

I have also updated the PR description now. I apologize for missing that. I will link a couple of issues to document these changes in the CHANGELOG.

**Review by pengyin-shan — APPROVED** [review]

**Pull request merged**
